### ISSUE TITLE
[fj-doc-maven-plugin] Could not find goal 'verify'

### ISSUE THREAD

**Issue by amusarra** [fugerit-org/fj-doc#180]
When add  `fj-doc` configuration to an existing project by this command:

`mvn org.fugerit.java:fj-doc-maven-plugin:add -Dversion=8.6.0`

and then I run the command `mvn clean package`, I get the error:

`Could not find goal 'verify' in plugin org.fugerit.java:fj-doc-maven-plugin:8.6.0 among available goals add`

From the [documentation](https://github.com/fugerit-org/fj-doc/tree/v8.7.1/fj-doc-maven-plugin#available-goals) goal `verify` is available since version [8.7.0](https://github.com/fugerit-org/fj-doc/tree/v8.7.0/fj-doc-maven-plugin).

Since the maven plugin command specified version [8.6.0](https://github.com/fugerit-org/fj-doc/tree/v8.6.0/fj-doc-maven-plugin) I would have expected the plugin to be configured without the `verify` goal.

```xml
  <build>
    <plugins>
      <plugin>
        <groupId>org.fugerit.java</groupId>
        <artifactId>fj-doc-maven-plugin</artifactId>
        <version>${fj-doc-version}</version>
        <executions>
          <execution>
            <id>freemarker-verify</id>
            <phase>compile</phase>
            <goals>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <templateBasePath>${project.basedir}/src/main/resources/my-app/template</templateBasePath>
          <generateReport>true</generateReport>
          <failOnErrors>true</failOnErrors>
          <reportOutputFolder>${project.build.directory}/freemarker-syntax-verify-report</reportOutputFolder>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

Here you can see how to replicate the use case.

[![asciicast](https://asciinema.org/a/MpB4fbublGhSuCbCyZWSFZxbf.svg)](https://asciinema.org/a/MpB4fbublGhSuCbCyZWSFZxbf)

---
My Environment:
- OS: 23.6.0 Darwin Kernel Version 23.6.0 (Sonoma 14.6.1 (23G93))
- Java(TM) SE Runtime Environment Oracle GraalVM 21.0.2+13.1 (build 21.0.2+13-LTS-jvmci-23.1-b30)
- Maven: Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
---

**Comment by fugerit79** [comment]
Thanks for trying the plugin @amusarra .
Actually here the issue here is using the latest version of the maven plugin (8.7.4 at the moment) targeting a previous version of the libraruy 8.6.0.
The code is generated from the current version, but then it's run with the old one.

Even though possible, it is not a recommended (I updated the documentation) : 
- next patch will contains a workaround (see PR https://github.com/fugerit-org/fj-doc/pull/181)
- as a common guideline, when adding the configuration to an existing project it is preferred to use the latest version.

Thanks again.

**Comment by fugerit79** [comment]
Thanks, done https://github.com/fugerit-org/fj-doc/releases/tag/v8.7.5
